# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.loader.grub = {
    enable = true;
    zfsSupport = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    mirroredBoots = [
      {
        devices = ["nodev"];
        path = "/boot";
      }
    ];
  };

  boot.initrd.availableKernelModules = ["nvme" "mpt3sas" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd" "it87" "tcp_bbr"];
  boot.extraModulePackages = [];
  # mitigations=off is DANGEROUS.
  boot.kernelParams = ["nohibernate" "mitigations=off"];

  fileSystems."/" = {
    device = "wonderland/root";
    fsType = "zfs";
  };

  fileSystems."/var" = {
    device = "wonderland/var";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "wonderland/nix";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "wonderland/home";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2B2B-5D75";
    fsType = "vfat";
  };

  # swapDevices = [ "/dev/disk/by-label/swap1" "/dev/disk/by-label/swap2" ];

  #boot.zfs.extraPools = [ "media" ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;

  networking.hostId = "8425e349";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
